//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobSearch.WEB.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажити резюме.
        /// </summary>
        public static string Button_DownloadResume {
            get {
                return ResourceManager.GetString("Button_DownloadResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВІДГУКНУТИСЯ.
        /// </summary>
        public static string Button_Respond {
            get {
                return ResourceManager.GetString("Button_Respond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відгуки.
        /// </summary>
        public static string Button_Reviews {
            get {
                return ResourceManager.GetString("Button_Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переглянути і відгукнутися.
        /// </summary>
        public static string Button_ViewAndRespond {
            get {
                return ResourceManager.GetString("Button_ViewAndRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заповніть обов&apos;язкові поля та прикріпіть своє резюме.
        /// </summary>
        public static string Error_FillRequiredFieldsAndAttachResume {
            get {
                return ResourceManager.GetString("Error_FillRequiredFieldsAndAttachResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль має містити від 6 до 50 символів..
        /// </summary>
        public static string Error_PasswordMustContain {
            get {
                return ResourceManager.GetString("Error_PasswordMustContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле є обов&apos;язковим..
        /// </summary>
        public static string Error_RequiredField {
            get {
                return ResourceManager.GetString("Error_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неможливо ідентифікувати користувача. Перевірте введені дані та спробуйте знову..
        /// </summary>
        public static string Error_UserNotIdentified {
            get {
                return ResourceManager.GetString("Error_UserNotIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-2 роки.
        /// </summary>
        public static string From1To2Years {
            get {
                return ResourceManager.GetString("From1To2Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-5 років.
        /// </summary>
        public static string From3To5Years {
            get {
                return ResourceManager.GetString("From3To5Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повна зайнятість.
        /// </summary>
        public static string FullEmployment {
            get {
                return ResourceManager.GetString("FullEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стажування.
        /// </summary>
        public static string Internship {
            get {
                return ResourceManager.GetString("Internship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Супровідний лист.
        /// </summary>
        public static string Lable_CoverLetter {
            get {
                return ResourceManager.GetString("Lable_CoverLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити нову вакансію.
        /// </summary>
        public static string Lable_CreateVacancy {
            get {
                return ResourceManager.GetString("Lable_CreateVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата створення.
        /// </summary>
        public static string Lable_CreationDate {
            get {
                return ResourceManager.GetString("Lable_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string Lable_Delete {
            get {
                return ResourceManager.GetString("Lable_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        public static string Lable_Description {
            get {
                return ResourceManager.GetString("Lable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        public static string Lable_Edit {
            get {
                return ResourceManager.GetString("Lable_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна пошта.
        /// </summary>
        public static string Lable_Email {
            get {
                return ResourceManager.GetString("Lable_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид зайнятості.
        /// </summary>
        public static string Lable_EmploymentType {
            get {
                return ResourceManager.GetString("Lable_EmploymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Досвід.
        /// </summary>
        public static string Lable_Experience {
            get {
                return ResourceManager.GetString("Lable_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубліковано.
        /// </summary>
        public static string Lable_IsPublished {
            get {
                return ResourceManager.GetString("Lable_IsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        public static string Lable_Name {
            get {
                return ResourceManager.GetString("Lable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Lable_Password {
            get {
                return ResourceManager.GetString("Lable_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата публікації.
        /// </summary>
        public static string Lable_PublicationDate {
            get {
                return ResourceManager.GetString("Lable_PublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВІДГУКНУТИСЯ НА ВАКАНСІЮ.
        /// </summary>
        public static string Lable_RespondToTheVacancy {
            get {
                return ResourceManager.GetString("Lable_RespondToTheVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резюме.
        /// </summary>
        public static string Lable_Resume {
            get {
                return ResourceManager.GetString("Lable_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string Lable_Save {
            get {
                return ResourceManager.GetString("Lable_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід.
        /// </summary>
        public static string Lable_SignIn {
            get {
                return ResourceManager.GetString("Lable_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище.
        /// </summary>
        public static string Lable_Surname {
            get {
                return ResourceManager.GetString("Lable_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        public static string Lable_Title {
            get {
                return ResourceManager.GetString("Lable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат роботи.
        /// </summary>
        public static string Lable_WorkFormat {
            get {
                return ResourceManager.GetString("Lable_WorkFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 1 року.
        /// </summary>
        public static string Less1Year {
            get {
                return ResourceManager.GetString("Less1Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5+ років.
        /// </summary>
        public static string More5Years {
            get {
                return ResourceManager.GetString("More5Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без досвіду.
        /// </summary>
        public static string NoExperience {
            get {
                return ResourceManager.GetString("NoExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В офісі/на місці.
        /// </summary>
        public static string OfficeWork {
            get {
                return ResourceManager.GetString("OfficeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неповна зайнятість.
        /// </summary>
        public static string PartTimeEmployment {
            get {
                return ResourceManager.GetString("PartTimeEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Віддалена робота.
        /// </summary>
        public static string RemoteWork {
            get {
                return ResourceManager.GetString("RemoteWork", resourceCulture);
            }
        }
    }
}
